DB:
  mysql:
    database: erpsystem
    host: erpsystem-1.cc9d4uudotkz.ap-northeast-2.rds.amazonaws.com
    password: erp123456789!
    port: 3306
    user: admin
LOG:
  filename: api_gw.log
  filepath: ../log/
  level: INFO
  format: "%(asctime)s %(levelname)s - %(message)s"
PROCESS:
  ip: 172.31.9.78
  port: 18001