DB:
  mysql:
    database: erpsystem
    host: localhost
    password: erp123456789!
    port: 3306
    user: admin
LOG:
  filename: api_gw.log
  filepath: ../log/
  level: INFO
  format: "%(asctime)s %(levelname)s - %(message)s"
api_gw:
  ip: 172.31.9.78
  port: 18001
user_management:
  ip: 127.0.0.1
  port: 18002