DB:
  mysql:
    database: erpsystem
    host: localhost
    password: erp123456789!
    port: 3306
    user: admin
LOG:
  filepath: ../log/
  level: INFO
  format: "%(asctime)s %(levelname)s - %(message)s"
api_gw:
  ip: 172.31.34.56
  port: 18001
user_management:
  ip: 127.0.0.1
  port: 18002
community_management:
  ip: 127.0.0.1
  port: 18003
system_management:
  ip: 127.0.0.1
  port: 18004
goods_management:
  ip: 127.0.0.1
  port: 18005
etc_management:
  ip: 127.0.0.1
  port: 18006
consignment_management:
  ip: 127.0.0.1
  port: 18007